# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
#  - trigger: ":date"
#    replace: "{{mydate}}"
#    vars:
#      - name: mydate
#        type: date
#        params:
#          format: "%Y-%m-%d %T"
#          format: "%Y-%m-%d %H:%M:%S"
# コロンが消えてしまう
  - trigger: ":nowl"
    replace: "{{now}}"
    vars:
      - name: now
        type: shell
        params:
          cmd: "date \"+%Y-%m-%d %H:%M:%S\""
  - trigger: ":nowu"
    replace: "{{now}}"
    vars:
      - name: now
        type: shell
        params:
          cmd: "date -u \"+%Y-%m-%dT%H:%M:%SZ\""

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
